config/routes.rb
Rails.application.routes.draw do
  resources :registered_applications

  devise_for :users

  namespace :api, defaults: { format: :json } do
     match '/events', to: 'events#preflight', via: [:options]
     resources :events, only: [:create]
   end

  get 'welcome/index'
  get 'welcome/about'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :url, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registered_applications, dependent: :destroy

   attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validate :validate_username


  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
     conditions = warden_conditions.dup
     if login = conditions.delete(:login)
       where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
     else
       if conditions[:username].nil?
         where(conditions).first
       else
         where(username: conditions[:username]).first
       end
     end
  end

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
	skip_before_action :verify_authenticity_token
	skip_before_action :authenticate_user!
	before_action :set_access_control_headers

	 def set_access_control_headers
		 headers['Access-Control-Allow-Origin'] = '*'

		 headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'

		 headers['Access-Control-Allow-Headers'] = 'Content-Type'
	 end

   def create
		 registered_application = RegisteredApplication.find_by(url:request.env['HTTP_ORIGIN'])

		 if registered_application.nil?
			  return render json: "Unregistered application", status: :unprocessable_entity
		 end

		 @event = registered_application.events.build(event_params)

		 if @event.save
			 render json: @event, status: :created
		 else
			 render json: {errors: @event.errors}, status: :unprocessable_entity
		 end

   end

	 def preflight
		 head 200
	 end

	 private

	 def event_params
		 params.require(:event).permit(:name)
	 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :authenticate_user!, except: [:index, :about]
	

	protected

	def configure_permitted_parameters
		added_attrs = [:username, :email, :password, :password_confirmation]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    unless @registered_application.user == current_user
      flash[:alert] = "You are not authorized to view this app."
      redirect_to root_path
    end
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user

    if @registered_application.save
      flash[:notice] = "Your application has been registered."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error registering your app. Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.assign_attributes(registered_application_params)

    if @registered_application.save
      flash[:notice] = "Your application has been updated."
      redirect_to @registered_application
    else
      flash.now[:alert] = "There was an error updating your app. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was deleted."
      redirect_to registered_applications_path
    else
      flash[:alert] = "There was an error deleting your registered app."
      render :show
    end
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1"  />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocmetrics", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>

        <% if user_signed_in? %>
        <li><%= link_to "My Apps", registered_applications_path %></li>
        <li class="pull-right"><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <li class="pull-right"><%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %></li>
        <li class="pull-right nav-user">Signed in as: <strong><%= current_user.email %></strong> |</li>
        <% else %>
          <li class="pull-right"><%= link_to 'Sign in', new_user_session_path, class: 'navbar-link' %> </li>
          <li class="pull-right"> <%= link_to 'Sign up', new_user_registration_path, class: 'navbar-link' %>  </li>

        <% end %>
      </ul>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for @registered_application do |f| %>
	<% if @registered_application.errors.any? %>
		<div class="alert alert-danger">
			<h4><%= pluralize(@registered_application.errors.count, "error") %>.</h4>
				<ul>
					<% @registered_application.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %>

  <div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control', placeholder: "Enter your site's name here" %>
	</div>

	<div class="form-group">
	 	<%= f.label :url %>
	 	<%= f.text_field :url, class: 'form-control', placeholder: "Enter your site's full URL here" %>
 	</div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
		<%= link_to 'Cancel', registered_applications_path, class: 'btn btn-cancel' %>
  </div>
<% end %>

app/views/registered_applications/edit.html.erb
<div class="container-fluid app new">
  <h1>Edit <%=@registered_application.name%></h1>
  <div class="row">
  	<div class="col-8">
  		<%= render "form" %>
  	</div>
  </div>
</div>

app/views/registered_applications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Registered Applications</h1>
    </div>

    <div class="col button new_app">
      <%= link_to "Register a New Application", new_registered_application_path, class: 'btn btn-success' %>
    </div>
  </div>
  <div class="row app index_list">
  	<div class="col">
  		<% if current_user.registered_applications.any? %>
  			<% current_user.registered_applications.each do |app| %>
  				<h4><%= link_to app.name, app %></h4>
  			<% end %>
  		<% else %>
  			<p>You have no registered applications at this time.</p>
  		<% end %>
  	</div>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="container-fluid app new">
  <h1>New Application Registration Form</h1>
  <div class="row">
  	<div class="col-8">
  		<%= render "form" %>
  	</div>
  </div>
</div>

app/views/registered_applications/show.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<div class="jumbotron" >
	<h1><%= @registered_application.name %></h1>
	<div class="row">
		<h4 class="lead "><%= link_to @registered_application.url, "#{@registered_application.url}", target: "_blank"%></h4> <br />
	</div>
	<div class="btn-group">
		<%= link_to "Edit", edit_registered_application_path(@registered_application), class: 'btn btn-success' %>
		<%= link_to "Delete", @registered_application, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to remove this application?'} %>
	</div>
	<hr class="my-2">

</div>

<div>
	<table class="table table-hover">
		<thead >
			<tr>
				<th>Event</th>
				<th class="count">Count</th>
			</tr>
		</thead>
		<tbody>
			<% @events.each do |event, event_count | %>
				<tr>
					<td><%= event %></td>
					<td><%= event_count.length %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<div class = "event_visual">
			<% if @registered_application.events.count > 0 %>
		<div class = "col-md-6">
				<%= pie_chart @registered_application.events.group(:name).count %>
		</div>
		<div class = "col-md-6">
				<%= line_chart @registered_application.events.group_by_day(:created_at, range: 2.weeks.ago.midnight..Time.now).count %>
		</div>
			<% end %>
	</div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>Analyze data for free on your business apps!</p>
  <p>
    <%= link_to 'Sign in', new_user_session_path, class: 'navbar-link' %> or
    <%= link_to "Sign Up",  new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>